Update linux version to 1.0.1.346.

diff --git a/tools/build/update_install b/tools/build/update_install
--- a/tools/build/update_install
+++ b/tools/build/update_install
@@ -1,111 +1,185 @@
 #!/bin/bash
 
 FILE=/etc/systemd/system/aliyun.service
+aliyun_service_name='aliyun-service'
+aliyun_service_bin="/usr/sbin/$aliyun_service_name"
 
-
-if [ -e /usr/sbin/aliyun-service ]; then
-  if [ -e $FILE ]; then
-    rm $FILE
-    touch $FILE
-    echo "[Unit]" >> $FILE
-    echo "Description=auto run aliyunservice or agent" >> $FILE
-    echo "[Service]" >> $FILE
-    echo "Type=simple" >> $FILE
-    echo "ExecStart=/usr/sbin/aliyun-service" >> $FILE
-    echo "Restart=always " >> $FILE
-    echo "KillMode=process " >> $FILE
-    echo "RestartSec=1" >> $FILE
-    echo "[Install]" >> $FILE
-    echo "WantedBy=multi-user.target" >> $FILE
-    /bin/systemctl daemon-reload
-  fi
-
-
-  if [ -e /etc/init.d/agentwatch ]; then
-    grep -q 'echo "KillMode=process " >> $FILE'  /etc/init.d/agentwatch
-    if  [ $?  -ne  0 ]; then
-      grep -q 'echo "Restart=always " >> $FILE'  /etc/init.d/agentwatch
-      if  [ $?  -eq  0 ]; then
-        sed -i '/echo "Restart=always " >> $FILE/a\echo "KillMode=process " >> $FILE' /etc/init.d/agentwatch
-      fi
+stop_service() {
+    # For SUSE
+    if [ -e /etc/inittab ]; then
+        result=`cat /etc/inittab | grep "$aliyun_service_name"`
+        if [ $? -eq 0 ]; then
+            sed -i /$aliyun_service_name/d /etc/inittab
+            # This file will be occupied by aliyun-service on SUSE 11
+            if [ -e /var/tmp/aliyun_assist_update.lock ]; then
+                rm -f /var/tmp/aliyun_assist_update.lock
+            fi
+            kill -HUP 1
+            return
+        fi
     fi
-  fi
+    
+    for service_pid in `ps axf | grep "$aliyun_service_bin" | grep -v grep | awk {'print $1'}`
+    do
+        kill -9 $service_pid
+    done
+}
 
-  assist_version=$(cat /usr/local/share/aliyun-assist/version)
-  data_dir="/usr/local/share/aliyun-assist/$assist_version"
+clean() {
+    # This file exist in offcial suse image, it cause conflict
+    [ -e "/usr/lib/systemd/system/aliyun.service" ] && rm -rf /usr/lib/systemd/system/aliyun.service
+    
+    [ -e "/var/lock/agentwatch" ] && rm -f "/var/lock/agentwatch"
+    
+    #remove old agentwatch first
+    if [ -e /etc/init.d/agentwatch ]; then
+        CHK=$(which chkconfig)
+        if [ ! -x "${CHK}" ]; then
+            echo "No find chkconfig"
+            URC=$(which update-rc.d)
+            if [ -x "${URC}" ]; then
+                echo "Find update-rc.d"
+                update-rc.d -f agentwatch remove
+            fi
+        else
+            echo "Find chkconfig"
+            chkconfig --del agentwatch
+        fi
+        
+        rm -rf /etc/init.d/agentwatch
+    fi
+}
 
-  chmod a+x $data_dir/aliyun_assist_update
-  chmod a+x $data_dir/aliyun_installer
-  chmod a+x $data_dir/aliyun-service
+clean
+if [ -e /usr/sbin/aliyun-service ]; then
+    if [ -e $FILE ]; then
+        rm $FILE
+        touch $FILE
+        echo "[Unit]" >> $FILE
+        echo "Description=auto run aliyunservice or agent" >> $FILE
+        echo "[Service]" >> $FILE
+        echo "Type=simple" >> $FILE
+        echo "ExecStart=/usr/sbin/aliyun-service" >> $FILE
+        echo "Restart=always " >> $FILE
+        echo "KillMode=on-failure" >> $FILE
+        echo "RestartSec=1min" >> $FILE
+        echo "[Install]" >> $FILE
+        echo "WantedBy=multi-user.target" >> $FILE
+        /bin/systemctl daemon-reload
+    fi
 
-  ln -sf /usr/local/share/aliyun-assist/$assist_version/aliyun-service /usr/sbin/aliyun-service
-  ln -sf /usr/local/share/aliyun-assist/$assist_version/aliyun_installer /usr/sbin/aliyun_installer
+    assist_version=$(cat /usr/local/share/aliyun-assist/version)
+    data_dir="/usr/local/share/aliyun-assist/$assist_version"
+
+    chmod a+x $data_dir/aliyun_assist_update
+    chmod a+x $data_dir/aliyun_installer
+    chmod a+x $data_dir/aliyun-service
+
+    ln -sf /usr/local/share/aliyun-assist/$assist_version/aliyun-service /usr/sbin/aliyun-service
+    ln -sf /usr/local/share/aliyun-assist/$assist_version/aliyun_installer /usr/sbin/aliyun_installer
+
+    cmd="systemctl restart aliyun.service"
+    $cmd
+    rc=$?
+    if [ ${rc} -eq 0 ] ;then
+        echo $cmd
+        exit 0
+    fi
   
-  cmd="systemctl restart aliyun.service"
-  $cmd
-  rc=$?
-  if [ ${rc} -eq 0 ] ;then
-    echo $cmd
-    exit 0
-  fi
+    if [ -f /etc/init.d/aliyun-service ]; then
+        /etc/init.d/aliyun-service restart
+        CHK=$(which chkconfig)
+        if [ ! -x "${CHK}" ]; then
+            echo "No find chkconfig"
+            URC=$(which update-rc.d)
+            if [ -x "${URC}" ]; then
+                echo "Find update-rc.d"
+                update-rc.d aliyun-service defaults
+            fi
+        else
+            echo "Find chkconfig"
+            chkconfig --add aliyun-service
+            chkconfig aliyun-service on
+        fi
+        exit 0
+    fi
   
-  if [ -f /etc/init/aliyun-service.conf ]; then
-          grep -i "Ubuntu" /etc/issue
-          if [ $? -eq 0 ]; then
-                cmd="/sbin/initctl restart aliyun-service"
-                $cmd
-                rc=$?
-                if [ ${rc} -eq 0 ] ;then
-                  echo $cmd
-                  exit 0
-                fi
-                service agentwatch restart
+    if [ -f /etc/init/aliyun-service.conf ]; then
+        grep -i "Ubuntu" /etc/issue
+        if [ $? -eq 0 ]; then
+            cmd="/sbin/initctl restart aliyun-service"
+            $cmd
+            rc=$?
+            if [ ${rc} -eq 0 ] ;then
+                echo $cmd
                 exit 0
-          else
-                setsid /sbin/initctl restart aliyun-service
-                exit 0
-          fi
-  fi
+            fi
+            exit 0
+        else
+            setsid /sbin/initctl restart aliyun-service
+            exit 0
+        fi
+    fi
   
-  
-  if echo $init_path | grep -q 'systemd' &&   [[ -d /var/run/systemd/system ]] ; then
-     systemctl restart agentwatch
-  else
-     service agentwatch restart
-  fi
-
+    src_dir="$data_dir/init"
+    . $src_dir/init-functions
+    if detect_systemd; then
+        cp -f $src_dir/aliyun.service /etc/systemd/system/aliyun.service
+        systemctl daemon-reload
+        systemctl enable aliyun.service
+        stop_service
+        systemctl restart aliyun.service
+    elif detect_sysvinit; then
+        cp -f $src_dir/aliyun-service /etc/init.d/aliyun-service
+        chmod 755 /etc/init.d/aliyun-service
+        CHK=$(which chkconfig)
+        if [ ! -x "${CHK}" ]; then
+            echo "No find chkconfig"
+            URC=$(which update-rc.d)
+            if [ -x "${URC}" ]; then
+                echo "Find update-rc.d"
+                update-rc.d aliyun-service defaults
+            fi
+        else
+            echo "Find chkconfig"
+            chkconfig --add aliyun-service
+            chkconfig aliyun-service on
+        fi
+        stop_service
+        /etc/init.d/aliyun-service restart
+    fi
 
 
 elif [ -e /opt/sbin/aliyun-service ]; then
-  if [ -e $FILE ]; then
-    rm $FILE
-    touch $FILE
-    echo "[Unit]" >> $FILE
-    echo "Description=auto run aliyunservice or agent" >> $FILE
-    echo "[Service]" >> $FILE
-    echo "Type=simple" >> $FILE
-    echo "ExecStart=/opt/sbin/aliyun-service" >> $FILE
-    echo "Restart=always " >> $FILE
-    echo "KillMode=process " >> $FILE
-    echo "RestartSec=1" >> $FILE
-    echo "[Install]" >> $FILE
-    echo "WantedBy=multi-user.target" >> $FILE
-    /bin/systemctl daemon-reload
-  fi
-  
-  assist_version=$(cat /opt/local/share/aliyun-assist/version)
-  data_dir="/opt/local/share/aliyun-assist/$assist_version"
+    if [ -e $FILE ]; then
+        rm $FILE
+        touch $FILE
+        echo "[Unit]" >> $FILE
+        echo "Description=auto run aliyunservice or agent" >> $FILE
+        echo "[Service]" >> $FILE
+        echo "Type=simple" >> $FILE
+        echo "ExecStart=/opt/sbin/aliyun-service" >> $FILE
+        echo "Restart=on-failure" >> $FILE
+        echo "KillMode=process " >> $FILE
+        echo "RestartSec=1min" >> $FILE
+        echo "[Install]" >> $FILE
+        echo "WantedBy=multi-user.target" >> $FILE
+        /bin/systemctl daemon-reload
+    fi
 
-  chmod a+x $data_dir/aliyun_assist_update
-  chmod a+x $data_dir/aliyun_installer
-  chmod a+x $data_dir/aliyun-service
+    assist_version=$(cat /opt/local/share/aliyun-assist/version)
+    data_dir="/opt/local/share/aliyun-assist/$assist_version"
 
-  ln -sf /opt/local/share/aliyun-assist/$assist_version/aliyun-service /opt/sbin/aliyun-service
-  ln -sf /opt/local/share/aliyun-assist/$assist_version/aliyun_installer /opt/sbin/aliyun_installer
-  
-  systemctl restart aliyun.service
-  systemctl restart gshell.service
-  exit 0
+    chmod a+x $data_dir/aliyun_assist_update
+    chmod a+x $data_dir/aliyun_installer
+    chmod a+x $data_dir/aliyun-service
+
+    ln -sf /opt/local/share/aliyun-assist/$assist_version/aliyun-service /opt/sbin/aliyun-service
+    ln -sf /opt/local/share/aliyun-assist/$assist_version/aliyun_installer /opt/sbin/aliyun_installer
+
+    systemctl restart aliyun.service
+    systemctl restart gshell.service
+    exit 0
 fi
 
 
