Update version to 1.0.1.259.

diff --git a/init/install_service b/init/install_service
--- a/init/install_service
+++ b/init/install_service
@@ -12,16 +12,54 @@ echo "issue:$issue"
 
 
 if [ ! -e $script_dir/script/$issue/common/update_service ]; then
-    echo "3131:failed to find update script."
+    #echo "find update script."
     #exit 1
+    . "$script_dir/script/update_service"
+    if [ $? -ne 0 ]; then
+        echo "3131:failed to find update install script."
+        #exit 1
+    fi
 else
     ######### compare the pv in vm and newest pv##########
     . "$script_dir/script/$issue/common/update_service"
     if [ $? -ne 0 ]; then
-        echo "3131:failed to find update gshelld script."
+        echo "3131:failed to find update install script."
         #exit 1
     fi
 fi
 
-/etc/init.d/agentwatch reload
+if [ -e /etc/systemd/system/aliyun.service ]; then
+  cmd="systemctl restart aliyun.service"
+  $cmd
+  rc=$?
+  if [ ${rc} -eq 0 ] ;then
+    echo $cmd
+    exit 0
+  fi
+fi
+
+if [ -f /etc/init/aliyun-service.conf ]; then
+        grep -i "Ubuntu" /etc/issue
+        if [ $? -eq 0 ]; then
+              cmd="/sbin/initctl restart aliyun-service"
+              $cmd
+              rc=$?
+              if [ ${rc} -eq 0 ] ;then
+                echo $cmd
+                exit 0
+              fi
+              service agentwatch restart
+              exit 0
+        else
+              setsid /sbin/initctl restart aliyun-service
+              exit 0
+        fi
+fi
+
+
+if echo $init_path | grep -q 'systemd' &&   [[ -d /var/run/systemd/system ]] ; then
+   systemctl restart agentwatch
+else
+   service agentwatch restart
+fi
 #echo "0:success"
diff --git a/init/script/common/identify_issue_version b/init/script/common/identify_issue_version
--- a/init/script/common/identify_issue_version
+++ b/init/script/common/identify_issue_version
@@ -721,9 +721,9 @@ function get_issue_version()
     big_enable=1
     small_enable=1
     if [ "$enable_file" == "" ]; then
-        glogger -o "[`now`] failed to find the issue info file" -t $default_time 1>/dev/null 2>&1
+        #glogger -o "[`now`] failed to find the issue info file" -t $default_time 1>/dev/null 2>&1
         echo "failed to find $issue version"
-        exit 1
+        #exit 1
     fi
     if [ "$enable_file" == "$des_dir/etc/issue" ]; then
         big=`cat $enable_file | head -n 1 | awk -F'.' {'print $1'} | awk {'print $NF'}`
@@ -880,9 +880,9 @@ get_issue_version
 
 
 if [ "$issue" = "" -o "$issue_version" = "" ]; then
-    glogger -o "[`now`] 3119:failed to parse issue $issue and issue_version $issue_version" -t $default_time 1>/dev/null 2>&1
+   # glogger -o "[`now`] 3119:failed to parse issue $issue and issue_version $issue_version" -t $default_time 1>/dev/null 2>&1
     echo "3119:failed to parse issue $issue and issue_version $issue_version"
-    exit 1
+   # exit 1
 fi
 
 
